version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: schooldb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schooldb"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://schooladmin:schoolpw123@postgres:5432/schooldb
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: